### ISSUE TITLE
OkexSocketClient is not working using DemoTradingService 

### ISSUE THREAD

**Issue by lcmgbra** [burakoner/OKEx.Net#38]
Hi Burakoner.  How are you? it's me again...

I don't know if I'm doing something wrong.., but this method "ws.SubscribeToOrderUpdates(OkexInstrumentType.Spot" doesn't work using DemoTradingService."
     var ws = new OkexSocketClient(new Okex.Net.CoreObjects.OkexSocketClientOptions()
            {
                AutoReconnect = true,
                DemoTradingService = demoTrading,
                LogLevel = LogLevel.Debug,
                ReconnectInterval = new TimeSpan(0, 1, 0),
                SocketResponseTimeout = new TimeSpan(0, 0, 30),
                SocketNoDataTimeout = new TimeSpan(0, 0, 30),
            });
            ws.SetApiCredentials(apiKey,apiSecret,apiPhrase);   
    ws.SubscribeToOrderUpdates(OkexInstrumentType.Spot, "INSTRUMENT", "UNDERLYING", (data) =>
            {
                if (data != null)
                {
                    Console.WriteLine(" Updated something ");
                }
            });
         await Task.Delay(10000);
..... put the order.....
I'm placing the order normal using api.PlaceOrder
Thanks.

**Comment by burakoner** [comment]
In fact it works. While I am investigating I saw connection ends in 30 seconds. If order updates comes in 30 seconds there is no problem but after. So I'll focus on why socket connection is closing.

**Comment by burakoner** [comment]
Check out https://github.com/burakoner/OKEx.Net/commit/74d079e99887a583ebb85f6c4e54c86125c544b1 and https://www.nuget.org/packages/OKEx.Net/5.1.1

This will fix problem partially, probably will fix your problem perfectly. But there can be a problem if there are many many subscriptions. So I wrote to JKorf to add a new method into CryptoExchange.Net It will solve the problem.

But I am repeating, for a normal user if you dont listen over 100-200 channels you wont feel problem.

**Comment by burakoner** [comment]
It has been fixed in https://github.com/burakoner/OKEx.Net/commit/dbecf251b77e7805cca072a554d2a4b1c29c9f70 and https://www.nuget.org/packages/OKEx.Net/5.1.2 completely.

**Comment by lcmgbra** [comment]
Unfortunately, I still don't receive update response.
I'm putting the order as follow:
var trade_01 = api.PlaceOrder("BTC-USDT", OkexTradeMode.Cash, OkexOrderSide.Buy, OkexPositionSide.Net, OkexOrderType.MarketOrder, 105.0m); 
trade_01.Success is true;

before  code above I'm creating ws as follow.
var ws = new OkexSocketClient(new Okex.Net.CoreObjects.OkexSocketClientOptions()
            {
                DemoTradingService = demoTrading,  // set true value
            });
            ws.SetApiCredentials(apiKey,apiSecret,apiPhrase);

**Comment by burakoner** [comment]
You have to start listen before placing order. Also You need to be listining while you are placing an order. So I advice to test you application part by part. Write a web socket listener code and run your application thn go to OKEx exchange in your browser and place order via internet browser. You'll see that you are getting updates. On the other hand if you want to place order and listen updates in same application you need to create different threads for these functions.

**Comment by lcmgbra** [comment]
Thanks you.

Yours sincerely,
Maria Gil.

**Comment by lcmgbra** [comment]
Just record... I'm using Threads and diffrents application. I tried using Okex exchange.  I have others listeners (public;SubscribeToTickers,etc... ) it' working very well, but update doen't work using DemoTrading.

**Comment by burakoner** [comment]
I really tested and got updates. I wouldn't insist if I wasn't sure. If you cant get updates, please write, maybe I can help

**Comment by lcmgbra** [comment]
can I send my code? it's small

**Comment by burakoner** [comment]
sure

**Comment by burakoner** [comment]
Check this console example. Use your own demo API key

```C#
using Okex.Net;
using Okex.Net.CoreObjects;
using Okex.Net.Enums;
using System;
using System.Threading;

namespace ConsoleApp2
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var api = new OkexClient(new OkexRestClientOptions { DemoTradingService = true});
            api.SetApiCredentials("e6e8d20a-4cab-420f-****-24e7e926188a", "E511393AE71C17A290F81007****2ED0", "12345678");
            var ws = new OkexSocketClient(new OkexSocketClientOptions { DemoTradingService = true});
            ws.SetApiCredentials("e6e8d20a-4cab-420f-****-24e7e926188a", "E511393AE71C17A290F81007****2ED0", "12345678");

            Console.WriteLine("Starting...");
            ws.SubscribeToOrderUpdates(OkexInstrumentType.Spot, null, null, (data) =>
            {
                if (data != null)
                {
                    Console.WriteLine("Instrument: " + data.Instrument);
                    Console.WriteLine("Order ID: " + data.OrderId);
                    Console.WriteLine("Order Side: " + data.OrderSide);
                    Console.WriteLine("Order Type: " + data.OrderType);
                    Console.WriteLine("Order State: " + data.OrderState);
                    Console.WriteLine("Quantity: " + data.Quantity);
                }
            });

            // Wait for establishing connection..
            Thread.Sleep(1000);

            Console.WriteLine("Listening...");
            Console.WriteLine("Press ENTER to place order");
            Console.ReadLine();

            // Place Order
            var order = api.PlaceOrder("BTC-USDT", OkexTradeMode.Cash, OkexOrderSide.Buy, OkexPositionSide.Net, OkexOrderType.MarketOrder, 100.0m);


            Console.ReadLine();
            Console.WriteLine("Closing...");
        }
    }
}
```

**Comment by lcmgbra** [comment]
Dear, Burakoner. 
I believe you.
My code is very similar than you code.

        private static async Task UpdateOrder()
        {
            var subs = new List<UpdateSubscription>();
            var ws = new OkexSocketClient(new Okex.Net.CoreObjects.OkexSocketClientOptions()
            {
                DemoTradingService = demoTrading, // true
            });
            ws.SetApiCredentials(apiKey, apiSecret, apiPhrase);

            ws.SubscribeToOrderUpdates(OkexInstrumentType.Spot, null, null, (data) =>      {
                   if (data != null)
                   {
                       Console.WriteLine(" Updated something ");
                   }
               });
        }

**Comment by lcmgbra** [comment]
I will take your code e run here and come back to you.

**Comment by lcmgbra** [comment]
I will re-install the package Okex.net

**Comment by lcmgbra** [comment]
private static async Task CreateOrder()
        {
            OkexClient api = new OkexClient(new Okex.Net.CoreObjects.OkexRestClientOptions
            {
                DemoTradingService = demoTrading,
                LogLevel = LogLevel.Debug,
            });
            api.SetApiCredentials(apiKey, apiSecret, apiPhrase);
            var trade_01 = api.PlaceOrder("BTC-USDT", OkexTradeMode.Cash, OkexOrderSide.Buy, OkexPositionSide.Net, OkexOrderType.MarketOrder, 105.0m);
            if (trade_01.Success)
            {
                Console.WriteLine("Sucess ");
            }
            else
            {
                Console.WriteLine("Erro " + trade_01.Error);
            }
        }

**Comment by lcmgbra** [comment]
private static async Task Main(string[] args)
        {
            demoTrading = true;
            Task.Run(() => UpdateOrder());  //// Update
            await Task.Delay(5000);
            Task.Run(() => CreateOrder());  //// 

            //          await Spot();
            Console.ReadLine();
        }

**Comment by lcmgbra** [comment]
> I will re-install the package Okex.net

give me 10 minutes

**Comment by burakoner** [comment]
ok

**Comment by lcmgbra** [comment]
Burakoner, I can not explain, but, after Restart Computer, re-install de package Okex.net, everithing is okay now.
Thank you for the patience. Congratulations for the professionalism.
Best regards,
Maria Gil.

**Comment by burakoner** [comment]
Im happy with that. Happy coding..
