### ISSUE TITLE
PlaceAlgoOrder issue

### ISSUE THREAD

**Issue by arashreshadi** [burakoner/OKEx.Net#69]
Hi Dear Friends
i have a problem with PlaceAlgoOrder? it just works in trigger mode and i can not set TP and sl prices. does anybody have a working sample? it just return 1 as error

Thanks
Arash

**Comment by burakoner** [comment]
Fixed in version 5.2.6 
Github Commit: https://github.com/burakoner/OKEx.Net/commit/de2a4cd1b698433cf112177900e68435d9f4484e 
Nuget Package: https://www.nuget.org/packages/OKEx.Net/5.2.6

**Comment by arashreshadi** [comment]
Tnx Dear Burakoner

do you have any sample for placealgoorder with TP and SL? I have updated to 5.2.6 but still not working and the status of the response is false.
here is a sample : 
api.PlaceAlgoOrder( "XRP-USDT-SWAP", OkexTradeMode.Isolated, OkexOrderSide.Buy, OkexAlgoOrderType.Conditional,                200,  null,  false,   OkexPositionSide.Long,   null,  OkexAlgoPriceType.Last,  0.24m, 0.25m, OkexAlgoPriceType.Last, 0.10m,                 0.10m,    0.18m,   0.18m  );
